module.exports = {
    geral: [
        "COMPUTADOR", "PROGRAMACAO", "DESENVOLVEDOR", "WHATSAPP", "BAILEYS",
        "PYTHON", "JAVASCRIPT", "TECLADO", "MONITOR", "CELULAR", "INTERNET",
        "NUVEM", "ALGORITMO", "INTELIGENCIA", "ARTIFICIAL", "ROBOTICA",
        "APLICATIVO", "CODIGO", "SISTEMA", "SOFTWARE", "HARDWARE", "SERVIDOR",
        "DADOS", "REDE", "BACKEND", "FRONTEND", "GITHUB", "FIREWALL", "BANCO",
        "MYSQL", "NODEJS", "HTML", "CSS", "VSCODE", "LINUX", "ANDROID", "IOS",
        "FRAMEWORK", "PLATAFORMA", "SENSOR", "AUTOMAÇÃO", "MACHINELEARNING",
        "IA", "GIT", "BUG", "DEPLOY", "API", "JSON", "SCRIPT", "PLUGINS"
    ],
    frutas: [
        "ABACAXI", "MORANGO", "BANANA", "LARANJA", "MACA", "UVA", "MANGA",
        "PERA", "KIWI", "CEREJA", "MELANCIA", "MARACUJA", "LIMAO", "COCO",
        "FIGO", "CAJU", "AMEIXA", "GRAVIOLA", "GOIABA", "PESSEGO", "JABUTICABA",
        "ACEROLA", "FRAMBOESA", "PITANGA", "PITAYA", "TAMARINDO", "ABACATE",
        "CARAMBOLA", "NECTARINA", "LICHIA", "CUPUACU", "BURITI", "BACABA",
        "MURICI", "INGA"
    ],
    animais: [
        "ELEFANTE", "GIRAFA", "LEAO", "TIGRE", "CACHORRO", "GATO", "PASSARO",
        "PEIXE", "COBRA", "MACACO", "PANDA", "LOBO", "RAPOSA", "URSO",
        "FOCA", "GOLFINHO", "TUBARAO", "BORBOLETA", "FORMIGA", "MOSQUITO",
        "ARANHA", "ZEBRA", "CAVALO", "GALINHA", "PATO", "CORUJA", "GALO",
        "VACA", "PORCO", "CARNEIRO", "JACARE", "CAMELO", "HIPOPOTAMO",
        "RINOCERONTE", "TAMANDUA", "QUATI", "SAGUI", "GAVIAO", "FALCAO"
    ],
    cores: [
        "AZUL", "VERMELHO", "AMARELO", "VERDE", "ROXO", "LARANJA", "PRETO",
        "BRANCO", "ROSA", "MARROM", "CINZA", "TURQUESA", "DOURADO", "PRATEADO",
        "ANIL", "CIANO", "VINHO", "BEGE", "SALMAO", "LILAS", "ESMERALDA",
        "CARAMELO", "MOSTARDA", "AZULMARINHO", "AZULCLARO", "VERDECLARO",
        "VERDEESCURO", "CASTANHO", "CREME"
    ],
    paises: [
        "BRASIL", "ARGENTINA", "CHINA", "JAPAO", "ESTADOS UNIDOS", "CANADA",
        "ALEMANHA", "FRANCA", "ESPANHA", "ITALIA", "PORTUGAL", "RUSSIA",
        "INDIA", "AUSTRALIA", "MEXICO", "CHILE", "EGITO", "SUECIA", "NORUEGA",
        "FINLANDIA", "DINAMARCA", "NIGERIA", "ANGOLA", "MOÇAMBIQUE", "ISLANDIA"
    ],
    cidades: [
        "SAO PAULO", "RIO DE JANEIRO", "RECIFE", "SALVADOR", "BELO HORIZONTE",
        "PORTO ALEGRE", "CURITIBA", "MANAUS", "FORTALEZA", "GOIANIA", "BRASILIA",
        "GARANHUNS", "CAMPINAS", "NATAL", "TERESINA", "MACAPA", "FLORIANOPOLIS"
    ],
    comidas: [
        "PIZZA", "HAMBURGUER", "LASANHA", "FEIJOADA", "CHURRASCO", "TACOS",
        "SUSHI", "RAVIOLI", "PANQUECA", "STROGONOFF", "PASTEL", "EMPADA",
        "FRANGO", "PEIXE", "CARNE", "BATATA", "ARROZ", "FEIJAO", "SALADA",
        "OMELETE", "PIPOCA", "BOLO", "TORTA", "BISCOITO", "SORVETE", "ACAI"
    ]
};
